name:production

on :
  push:
    branches:
      - main
  pull_request:
     branches:
     - main    

jobs:
   build:
     runs-on:ubuntu-latest
   steps:
      - name:Checkout code
        uses:actions/checkout@v3
      
      - name: setup node js
        uses: actions/setup-node@v3
        with:
          node-version:18 
          
      - name:install dependencies
        run:pnpm install 
       
      -name: run test  
       run :pnpm test

       - name: Build project
         run: pnpm run build   